# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='store.proto',
  package='store',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstore.proto\x12\x05store\"\x11\n\x0fGetPriceRequest\"!\n\x10GetPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x05\"#\n\x0fPurchaseRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"\"\n\x10PurchaseResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x0c\n\nEndRequest\"D\n\x0b\x45ndResponse\x12\x15\n\rstore_balance\x18\x01 \x01(\x05\x12\x1e\n\x16wallet_shutdown_status\x18\x02 \x01(\x05\x32\xbb\x01\n\x0cStoreService\x12;\n\x08GetPrice\x12\x16.store.GetPriceRequest\x1a\x17.store.GetPriceResponse\x12;\n\x08Purchase\x12\x16.store.PurchaseRequest\x1a\x17.store.PurchaseResponse\x12\x31\n\x08Shutdown\x12\x11.store.EndRequest\x1a\x12.store.EndResponseb\x06proto3'
)




_GETPRICEREQUEST = _descriptor.Descriptor(
  name='GetPriceRequest',
  full_name='store.GetPriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=39,
)


_GETPRICERESPONSE = _descriptor.Descriptor(
  name='GetPriceResponse',
  full_name='store.GetPriceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='store.GetPriceResponse.price', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=74,
)


_PURCHASEREQUEST = _descriptor.Descriptor(
  name='PurchaseRequest',
  full_name='store.PurchaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='store.PurchaseRequest.order_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=111,
)


_PURCHASERESPONSE = _descriptor.Descriptor(
  name='PurchaseResponse',
  full_name='store.PurchaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='store.PurchaseResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=147,
)


_ENDREQUEST = _descriptor.Descriptor(
  name='EndRequest',
  full_name='store.EndRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=161,
)


_ENDRESPONSE = _descriptor.Descriptor(
  name='EndResponse',
  full_name='store.EndResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_balance', full_name='store.EndResponse.store_balance', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wallet_shutdown_status', full_name='store.EndResponse.wallet_shutdown_status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['GetPriceRequest'] = _GETPRICEREQUEST
DESCRIPTOR.message_types_by_name['GetPriceResponse'] = _GETPRICERESPONSE
DESCRIPTOR.message_types_by_name['PurchaseRequest'] = _PURCHASEREQUEST
DESCRIPTOR.message_types_by_name['PurchaseResponse'] = _PURCHASERESPONSE
DESCRIPTOR.message_types_by_name['EndRequest'] = _ENDREQUEST
DESCRIPTOR.message_types_by_name['EndResponse'] = _ENDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPriceRequest = _reflection.GeneratedProtocolMessageType('GetPriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRICEREQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.GetPriceRequest)
  })
_sym_db.RegisterMessage(GetPriceRequest)

GetPriceResponse = _reflection.GeneratedProtocolMessageType('GetPriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRICERESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.GetPriceResponse)
  })
_sym_db.RegisterMessage(GetPriceResponse)

PurchaseRequest = _reflection.GeneratedProtocolMessageType('PurchaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _PURCHASEREQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.PurchaseRequest)
  })
_sym_db.RegisterMessage(PurchaseRequest)

PurchaseResponse = _reflection.GeneratedProtocolMessageType('PurchaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _PURCHASERESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.PurchaseResponse)
  })
_sym_db.RegisterMessage(PurchaseResponse)

EndRequest = _reflection.GeneratedProtocolMessageType('EndRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDREQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.EndRequest)
  })
_sym_db.RegisterMessage(EndRequest)

EndResponse = _reflection.GeneratedProtocolMessageType('EndResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDRESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:store.EndResponse)
  })
_sym_db.RegisterMessage(EndResponse)



_STORESERVICE = _descriptor.ServiceDescriptor(
  name='StoreService',
  full_name='store.StoreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=234,
  serialized_end=421,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrice',
    full_name='store.StoreService.GetPrice',
    index=0,
    containing_service=None,
    input_type=_GETPRICEREQUEST,
    output_type=_GETPRICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Purchase',
    full_name='store.StoreService.Purchase',
    index=1,
    containing_service=None,
    input_type=_PURCHASEREQUEST,
    output_type=_PURCHASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='store.StoreService.Shutdown',
    index=2,
    containing_service=None,
    input_type=_ENDREQUEST,
    output_type=_ENDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORESERVICE)

DESCRIPTOR.services_by_name['StoreService'] = _STORESERVICE

# @@protoc_insertion_point(module_scope)
